name: Deploy to Heroku Testing Environment

on: workflow_dispatch

jobs:
  deploy:
    environment: ljsimpleregisterlookup-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ vars.APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          # healthcheck: ${{ vars.APP_HEALTHCHECK_LINK }}
          # delay: 3
          dontuseforce: true