name: Deploy to Heroku Testing Environment

on: 
  push:
    branches: [ development ]

jobs:
  deploy:
    environment: ljsimpleregisterlookup-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ljsimpleregisterlookup-test"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          # healthcheck: "https://ljsimpleregisterlookup-test.herokuapp.com/" # Don't run healthcheck on test deployment, we may want to see errors in debug console or developer tools
          # delay: 3