name: Run Python Tests

on:
  workflow_dispatch:
  push:
    branches: [ python3 ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Python 3.10 and virtualenv, install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip'
        run: |
          pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Run Python Tests
        run: python runtests.py
