name: Run Python Tests and Deploy to Heroku Staging Environment

on:
  push:
    branches: [ main, ci]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python Tests
        run: python runtests.py

  deploy:
    needs: test # Wait until test job completes before deploying
    environment: ljsimpleregisterlookup-staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "ljsimpleregisterlookup-staging"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          healthcheck: "https://ljsimpleregisterlookup-staging.herokuapp.com/"
          delay: 3